[package]
name = "hwpb"
version = "0.1.0"
authors = ["Klemens Schölhorn <klemens@schoelhorn.eu>"]

[dependencies]
chrono = "0.3"
diesel = { version = "0.12.0", features = ["postgres", "chrono"] }
diesel_codegen = { version = "0.12.0", features = ["postgres"] }
dotenv = "0.8.0"
r2d2 = "0.7"
r2d2-diesel = "0.12"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket.git" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket.git", default_features = false, features = [ "json", "tera_templates" ] }
serde = "1.0"
serde_derive = "1.0"
