[production]
address = "localhost"
port = 8080
workers = 20

# generate using `openssl rand -base64 32`
secret_key = "*"

[global]
database = "postgres://user:password@host/database"
site_admins = [
    "user1",
    "user2",
]
ip_whitelisting = false
push_port = 8081
